version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Keep pull requests for GitHub Actions updated until merged
    open-pull-requests-limit: 10
    # Add labels to pull requests for GitHub Actions
    labels:
      - "dependencies"
      - "github-actions"