# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nyan < Formula
  desc "Colored cat command which supports syntax highlighting"
  homepage "https://github.com/toshimaru/nyan"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/toshimaru/nyan/releases/download/v1.1.0/nyan_Darwin_amd64.tar.gz"
      sha256 "74282c8fe6155b05b0d890449ea2bfcb8e05a7e91bdc03896e0c121cf5653d00"

      def install
        bin.install "nyan"
      end
    end
    on_arm do
      url "https://github.com/toshimaru/nyan/releases/download/v1.1.0/nyan_Darwin_arm64.tar.gz"
      sha256 "c539948c1a693a65865b95cd5b9e979073df66f360fcd3bbf94357898fba13f5"

      def install
        bin.install "nyan"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toshimaru/nyan/releases/download/v1.1.0/nyan_Linux_amd64.tar.gz"
        sha256 "1641a97f15f3d40d095eb4e29670ecda988433362269c353def73cc52fa37bd4"

        def install
          bin.install "nyan"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/toshimaru/nyan/releases/download/v1.1.0/nyan_Linux_arm64.tar.gz"
        sha256 "8aa4baa93a682181d17d7ddc78fe555def9977313cb58041119fd5f5f859ed16"

        def install
          bin.install "nyan"
        end
      end
    end
  end

  test do
    system "#{bin}/nyan", "-v"
  end
end
