# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nyan < Formula
  desc "Colored cat command which supports syntax highlighting"
  homepage "https://github.com/toshimaru/nyan"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toshimaru/nyan/releases/download/v1.0.1/nyan_Darwin_x86_64.tar.gz"
      sha256 "3ba0d5b11d76eae0c778913d602575919dc4963f9405a588704b094eb22cb002"

      def install
        bin.install "nyan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toshimaru/nyan/releases/download/v1.0.1/nyan_Darwin_arm64.tar.gz"
      sha256 "cda4b8bafcfffa5b12928810f05aa255166c58d7cc7c53b5247f394ff56fe542"

      def install
        bin.install "nyan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/toshimaru/nyan/releases/download/v1.0.1/nyan_Linux_x86_64.tar.gz"
      sha256 "c12f0b2cf7f5d850bc1d64771ba2d6d0302c6b72103be31e6b6310dd2ca3771d"

      def install
        bin.install "nyan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toshimaru/nyan/releases/download/v1.0.1/nyan_Linux_arm64.tar.gz"
      sha256 "dbd19e92be084ab919d5d20adc796c268105c08906c081c000a4e76b6718c7be"

      def install
        bin.install "nyan"
      end
    end
  end

  test do
    system "#{bin}/nyan", "-v"
  end
end
