# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nyan < Formula
  desc "Colored cat command which supports syntax highlighting"
  homepage "https://github.com/toshimaru/nyan"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toshimaru/nyan/releases/download/v1.0.7/nyan_Darwin_amd64.tar.gz"
      sha256 "4b96cbf45a1d04c42bbd2a930af4438ecda0f7688720e9685fd0569414c3ae49"

      def install
        bin.install "nyan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toshimaru/nyan/releases/download/v1.0.7/nyan_Darwin_arm64.tar.gz"
      sha256 "2d7a187abb33d838846dd0bccabc8f03f7477f073b9f1e38307b407d266d4e37"

      def install
        bin.install "nyan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/toshimaru/nyan/releases/download/v1.0.7/nyan_Linux_amd64.tar.gz"
      sha256 "fd9d7d47805fe1145707fe1b90aae5be2d97e03488f26a40aa31fd85cc84262a"

      def install
        bin.install "nyan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toshimaru/nyan/releases/download/v1.0.7/nyan_Linux_arm64.tar.gz"
      sha256 "642d147148bd5894862622bd31df22a5df1b716133981f09f5fb277a75bd6937"

      def install
        bin.install "nyan"
      end
    end
  end

  test do
    system "#{bin}/nyan", "-v"
  end
end
