# This file was generated by GoReleaser. DO NOT EDIT.
cask "nyan" do
  desc "Colorizing `cat` command with syntax highlighting"
  homepage "https://github.com/toshimaru/nyan"
  version "1.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nyan"

  on_macos do
    on_intel do
      url "https://github.com/toshimaru/nyan/releases/download/v1.2.3/nyan_Darwin_amd64.tar.gz"
      sha256 "798c575b7f9ab445e245ec21a67d2729a2b2e38db805f5a94622488ab5baa756"
    end
    on_arm do
      url "https://github.com/toshimaru/nyan/releases/download/v1.2.3/nyan_Darwin_arm64.tar.gz"
      sha256 "c325d37a6d5725f2f454850b5f81678383b2b01c519c2b58b73afcb12e4cdfa7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toshimaru/nyan/releases/download/v1.2.3/nyan_Linux_amd64.tar.gz"
      sha256 "115f2b940586f272e7bdd8ae92ea66faeccb0af398908fdb71b11bae4c38d9d5"
    end
    on_arm do
      url "https://github.com/toshimaru/nyan/releases/download/v1.2.3/nyan_Linux_arm64.tar.gz"
      sha256 "c4ebd098d4874df6574f800b30e27458be804614281edf255c15e49d77bc658c"
    end
  end

  # No zap stanza required
end
