# This file was generated by GoReleaser. DO NOT EDIT.
cask "nyan" do
  desc "Colored cat command which supports syntax highlighting"
  homepage "https://github.com/toshimaru/nyan"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nyan"

  on_macos do
    on_intel do
      url "https://github.com/toshimaru/nyan/releases/download/v1.2.0/nyan_Darwin_amd64.tar.gz"
      sha256 "ba838c6b8bcb78ee28709414ddfd9b6f59bbd7803ee5829580c544c3df4b8c9c"
    end
    on_arm do
      url "https://github.com/toshimaru/nyan/releases/download/v1.2.0/nyan_Darwin_arm64.tar.gz"
      sha256 "7679d6ec452064aa4d616336d467e830544c1a01ef9551a9d9404f50ff876f4a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/toshimaru/nyan/releases/download/v1.2.0/nyan_Linux_amd64.tar.gz"
      sha256 "4bebf0f2be3ed755fb7920baec900c7567ff62b4a74309de9aff4870b376c207"
    end
    on_arm do
      url "https://github.com/toshimaru/nyan/releases/download/v1.2.0/nyan_Linux_arm64.tar.gz"
      sha256 "ff956191dca2d2c0c12c2f2ffb4c4740d3df828fa2901992d8f016e099197734"
    end
  end

  # No zap stanza required
end
